"""create survey table

Revision ID: 1523552f0499
Revises: 8d67b8d6daef
Create Date: 2026-07-16 10:03:02.767146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1523552f0499'
down_revision: Union[str, Sequence[str], None] = '8d67b8d6daef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('quality_rating', sa.Integer(), nullable=False),
    sa.Column('outcome_rating', sa.Integer(), nullable=False),
    sa.Column('communication_rating', sa.Integer(), nullable=False),
    sa.Column('recommendation_rating', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('suggestions', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_id'), 'survey', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_id'), table_name='survey')
    op.drop_table('survey')
    # ### end Alembic commands ###
