"""Add reply column to feedback

Revision ID: 4c8d58510aa7
Revises: 730b3ee1e0e5
Create Date: 2026-07-13 01:35:30.865691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8d58510aa7'
down_revision: Union[str, Sequence[str], None] = '730b3ee1e0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('reply', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'reply')
    # ### end Alembic commands ###
