"""add assigned_to to feedback

Revision ID: ddb9074ea16b
Revises: e915841cc8ca
Create Date: 2026-07-15 22:52:27.640530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb9074ea16b'
down_revision: Union[str, Sequence[str], None] = 'e915841cc8ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'users', ['assigned_to'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'assigned_to')
    # ### end Alembic commands ###
